# Generated by Django 6.0 on 2026-01-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsapp', '0001_initial'),
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='receive_this_specific_newsletter_subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_newsletters', to=settings.AUTH_USER_MODEL),
        ),
    ]
