# Generated by Django 6.0 on 2026-01-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'role': 'EDITOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='collaborationinvitation',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='publishergroup',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='publishermember',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher'),
        ),
        migrations.AddField(
            model_name='publishermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='members',
            field=models.ManyToManyField(related_name='joined_publishers', through='publishers.PublisherMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'publisher')},
        ),
    ]
